<?php

/**
 * CUSTOM POST TYPE: LANDING PAGES
 * * Logic to move 'landing_pages' from /landing_pages/{slug}/ to /{slug}/
 * * Note: After adding this, you MUST go to Settings → Permalinks and click 
 * "Save Changes" to refresh the site's URL map.
 */

/**
 * 1. Update Permalink Generation
 * Strips the 'landing_pages' base from any URL generated by get_permalink()
 */
add_filter( 'post_type_link', function ( string $post_link, WP_Post $post ): string {
  if ( $post->post_type !== 'landing_pages' || 'publish' !== $post->post_status ) {
    return $post_link;
  }
  return home_url( '/' . $post->post_name . '/' );
}, 10, 2 );

/**
 * 2. Add Custom Rewrite Rule
 * Tells WordPress how to resolve a root-level URL to a Landing Page.
 * Uses 'bottom' priority to ensure standard Pages/Posts take precedence (Performance).
 */
add_action( 'init', function (): void {
  add_rewrite_rule(
    '^([^/]+)/?$',
    'index.php?landing_pages=$matches[1]',
    'top' // Changed from 'bottom' to 'top'
  );
} );

/**
 * 3. 301 Redirects (SEO Protection)
 * If someone visits the old /landing_pages/slug/ URL, redirect them to the new root URL.
 */
add_action( 'template_redirect', function (): void {
  // Only proceed if we are viewing a single 'landing_pages' post
  if ( ! is_singular( 'landing_pages' ) ) {
    return;
  }

  $post = get_queried_object();
  if ( ! $post instanceof WP_Post ) {
    return;
  }

  // Define the new clean URL
  $target_url = home_url( '/' . $post->post_name . '/' );

  // Get current URL for comparison
  $scheme      = is_ssl() ? 'https://' : 'http://';
  $host        = $_SERVER['HTTP_HOST'] ?? '';
  $request_uri = $_SERVER['REQUEST_URI'] ?? '';
  $current_url = strtok( $scheme . $host . $request_uri, '?' );

  $current_path = untrailingslashit( (string) parse_url( $current_url, PHP_URL_PATH ) );
  $target_path  = untrailingslashit( (string) parse_url( $target_url, PHP_URL_PATH ) );

  // Redirect if the user is using the old /landing_pages/ path
  if ( $current_path !== $target_path ) {
    wp_redirect( $target_url, 301 );
    exit;
  }
} );

/**
 * 4. Register the query var
 * This ensures WordPress recognizes 'landing_pages' in the URL string.
 */
add_filter( 'query_vars', function( $vars ) {
  $vars[] = 'landing_pages';
  return $vars;
} );